export const layoutStyles = {
    container: `modal-content bg-white h-max p-0 rounded-lg`,
    // container: `modal-content bg-white lg:shadow-md h-max p-3 lg:p-5 rounded-lg`,
    // container: `modal-content bg-white lg:shadow-md h-max p-3 lg:p-5 rounded-lg border border-borderColor`,
    // container: `bg-white lg:shadow-md h-max p-5 rounded-lg`,
    modalContainer: `p-5 py-20 lg:py-10 modal-content bg-white sm:h-max lg:w-5/12 w-screen h-screen overflow-y-scroll rounded-lg`,
    modalBody: `flex items-center justify-center fixed inset-0 z-50 bg-[#9095a0bf]`,
    main: `pt-20 w-screen px-5 lg:px-20 pb-56 sm:pb-0`,
    mainWrapper: `-mt-3 py-5 lg:min-h-[93vh] flex`,
    // comingSoonLabel: `fixed bottom-0 w-screen flex`,
    bottomNav: `flex items-center fixed justify-between bottom-0 w-screen left-0 bg-white border-t border-t-borderColor p-2 pl-5 lg:hidden`,
    // previewMainWrapper: `-mt-3 py-5 lg:min-h-[93vh] bg-brand`,
    previewMainWrapper: `-mt-3 py-10 lg:min-h-[93vh] flex justify-around`,
    textLg: `font-[CalFonts] text-3xl lg:text-5xl font-medium mb-10`,
    preview: `bg-white h-[80vh] w-full p-10 rounded-xl max-w-xl hidden lg:block`,
    projectCard: `m-2 mx-0 mb-5 p-2 rounded-xl`,
    projectThumbnail: `h-[350px] rounded-xl w-full object-cover`,
    loaderBody: `w-screen h-screen flex items-center justify-center`,
    loaderIcon: `-mt-5 -ml-12 h-10 w-10`
}